LCW.Catalog.Web/Controllers/ProductsController.cs
using LCW.Catalog.Web.Enums;
using LCW.Catalog.Web.Models;
using LCW.Catalog.Web.Response;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LCW.Catalog.Web.Controllers
{
    public class ProductsController : Controller
    {
        private readonly GetRequestBase _getRequestBase;
        private readonly PostRequestBase _postRequestBase;

        public ProductsController(GetRequestBase getRequestBase, PostRequestBase postRequestBase)
        {
            _getRequestBase = getRequestBase;
            _postRequestBase = postRequestBase;
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var categories = await _getRequestBase.SendGetRequest<List<CategoryDto>>("categories");

            ViewBag.categoryList = new SelectList(categories.Data, "Id", "Name");
            ViewBag.colors = new SelectList(Enum.GetValues(typeof(Color)));
            ViewBag.brands = new SelectList(Enum.GetValues(typeof(Brand)));
            ViewBag.status = new SelectList(Enum.GetValues(typeof(Status)));


            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Add(ProductAddDto productAddDto)
        {
            if (ModelState.IsValid)
            {
                var result = await _postRequestBase.SendPostRequest<NoDataResponse>("products/Create", productAddDto);

                if (result.ResultStatus == ResultStatus.Success)
                {
                    return Redirect("/Home/Index");
                }
            }

            var categories = await _getRequestBase.SendGetRequest<List<CategoryDto>>("categories");


            ViewBag.categoryList = new SelectList(categories.Data, "Id", "Name");
            ViewBag.colors = new SelectList(Enum.GetValues(typeof(Color)));
            ViewBag.brands = new SelectList(Enum.GetValues(typeof(Brand)));
            ViewBag.status = new SelectList(Enum.GetValues(typeof(Status)));

            return View(productAddDto);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(string productId)
        {
            var result = await _getRequestBase.SendGetRequest<ProductDto>("products/GetById?productId=" + productId);

            return View(result.Data);
        }

        [HttpPost]
        public async Task<IActionResult> MakeOffer(decimal price, string productId)
        {
            var data = new OfferDto { ProductId = productId, OfferedPrice = price };

            var result = await _postRequestBase.SendPostRequest<OfferDto>("offers/MakeAnOffer", data);

            return Redirect("/Home/Index");
        }

        [HttpGet]
        public async Task<IActionResult> Withdraw(string productId)
        {
            var result = await _getRequestBase.SendGetRequest<ProductDto>("offers/WithdrawOffer?productId=" + productId);

            return Redirect("/Home/Index");
        }

        [HttpPost]
        public async Task<IActionResult> Buy(decimal price, string Id)
        {
            var data = new OfferDto { OfferedPrice = price, ProductId = Id };
    
            var result = await _postRequestBase.SendPostRequest<OfferDto>("offers/Buy", data);

            return Redirect("/Home/Index");
        }
    }
}

LCW.Catalog.Web/Controllers/UserController.cs
using LCW.Catalog.Web.Models;
using LCW.Catalog.Web.Response;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.Extensions.Caching.Memory;

namespace LCW.Catalog.Web.Controllers
{
    public class UserController : Controller
    {

        private readonly GetRequestBase _getRequestBase;
        private readonly PostRequestBase _postRequestBase;
        private readonly IMemoryCache _memoryCache;

        public UserController(GetRequestBase getRequestBase, PostRequestBase postRequestBase, IMemoryCache memoryCache)
        {
            _getRequestBase = getRequestBase;
            _postRequestBase = postRequestBase;
            _memoryCache = memoryCache;
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SignUp(CreateUserDto createUserDto)
        {

            if (User.Identity.IsAuthenticated)
            {
                return Redirect("/Home/Index");
            }

            if (ModelState.IsValid)
            {
                await _postRequestBase.SendPostRequest<Response<UserDto>>("user/createuser", createUserDto);

                UserDto userDto = new UserDto { Email = createUserDto.Email, Password = createUserDto.Password, UserName = createUserDto.UserName };

                return await Login(userDto);

            }

            return View(createUserDto);
          
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserDto userDto)
        {

            if (User.Identity.IsAuthenticated)
            {
                return Redirect("/Home/Index");
            }

            if (ModelState.IsValid)
            {
                var result = await _postRequestBase.SendPostRequest<TokenDto>("auth/createtoken", userDto);

                if (result.Data is not null)
                {

                    MemoryCacheEntryOptions memoryCacheEntryOptions = new MemoryCacheEntryOptions
                    {
                        AbsoluteExpiration = DateTime.Now.AddMinutes(30),
                        Priority= CacheItemPriority.NeverRemove
                    };

                    _memoryCache.Set("Token", result.Data.AccessToken,memoryCacheEntryOptions);

                    List<Claim> claims = new List<Claim> {
                        new Claim(ClaimTypes.Name,userDto.Email),


                    };
                    var identity = new ClaimsIdentity(claims,
                          CookieAuthenticationDefaults.AuthenticationScheme);

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity));

                    return Redirect("/Home/Index");
                }

                ModelState.AddModelError("", "Bu bilgilerde bir kullanıcı bulunamadı");

                
            }

            return View(userDto);
        }



        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            _memoryCache.Remove("Token");

            return Redirect("/Home/Index");
        }



    }
}

LCW.Catalog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LCW.Catalog.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LCW.Catalog.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                        </li>

                        @if (!User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="SignUp">Üye Ol</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Login">Giriş Yap</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Index">Hesabım</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Products" asp-action="Add">Ürün Ekle</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Logout">Çıkış</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LCW.Catalog.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>